description = "Luis Pedro's personal luish configuration."

[dependencies]
std.bash-completion = "*"
std.git-completion = "*"

[alias]
"..." = "../.."
"...." = "../../.."
"....." = "../../../.."
"......" = "../../../../.."
"......." = "../../../../../.."
